export const sentences = [
    'As you please', "Oh, I am sorry. I have got a bit late", "I beg your pardon", "Would you please speak slowly ?", "It's all yours", "That's so kind of you", "Sorry for the inconvenience", "Nice to meet you", "Glad to meet you",
    "I will try my level best", "Please help yourself", "Well done, dear","Of Course", "By God's Grace", "Wonderful", 'Yes, by all means', "It’s on the tip of my tongue", "How can I go to the town centre?", "How was your weekend?", 
    'Apple today announced “Disney Melee Mania” from Mighty Bear Games will be joining the more than 200 incredibly fun games on its popular gaming subscription service, Apple Arcade',
    'Players will join forces in rumble-ready teams featuring iconic and fan-favorite Disney1 and Pixar1 characters, who will duke it out in a dazzling, never-before-seen virtual arena',
    'From Wreck-It Ralph, Elsa, and Mickey Mouse to Frozone, Moana, and Buzz Lightyear, each player will choose their unique holographic hero to battle in 3v3 matches with friends and foes as they vie to become the ultimate Disney champions',
      '“We’re thrilled to work with Disney to bring these beloved characters to the first-ever Disney and Pixar battle arena game, available exclusively on Apple Arcade,” said Simon Davis, Mighty Bear Games’ CEO',
    '“Fans will compete with arcade-style Disney and Pixar champions in a fun and frenzied all-out brawl to survive the chaotic melee and stay in the spotlight”',  'macOS Monterey delivers groundbreaking new features that help users connect in new ways, accomplish more, and work seamlessly across their Apple devices',
    'FaceTime includes new audio and video features that make calls feel more natural and lifelike, and new Continuity tools like AirPlay to Mac enable Apple devices to work even better together',
    'Live Text and Visual Lookup bring new intelligence features to surface useful information, Safari includes powerful tab organization with Tab Groups, and the ease of automation comes to the Mac with Shortcuts',
    'Coming later this fall, SharePlay will enable Mac users to have shared experiences together through FaceTime, and Universal Control will make it easy for users to work effortlessly across their Mac and iPad',
    'macOS Monterey is available today as a free software update on Macs with Apple silicon and Intel-based Macs',
    'FaceTime calls sound more natural and lifelike, and SharePlay offers a new way for users to connect and enjoy time with friends and family',
      'With spatial audio, voices in a FaceTime call sound like they are coming from where the person is positioned on the screen',
      'Two new microphone modes give users more control over how their voice sounds: Voice Isolation eliminates background noise to ensure the user’s voice is crystal clear, and Wide Spectrum allows all the noise to come in so participants can hear everything',
      'Portrait mode, a new feature in FaceTime and available in apps including Webex and Zoom, utilizes the Neural Engine in the M1 chip to keep the user in focus while blurring the background,2 and a new grid view shows participants of a Group FaceTime call in same-size tiles',
'A package manager is software that manages versions, packages and dependencies for your project',
  'When a project grows in scale, a package manager helps to manage dependencies',
  'It works perfectly across versions and even in collaborative projects',
  'It cuts costs by reducing dependency problems across developer teams.'
    ];